import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ArrowUpRight, BrainCircuit, Check, CheckCircle2, ChevronDown, Cloud, Code2, Globe2, Landmark, Menu, Network, PanelsTopLeft, ShieldCheck, Sparkles, Users, X } from 'lucide-react'
import './styles.css'

const solutions = [
  { number: '01', icon: Code2, accent: 'green', title: 'Produits digitaux', text: 'Des applications et plateformes pensées pour accélérer votre activité, de la première idée au produit qui compte.', tags: ['Web apps', 'Mobile', 'E-commerce'] },
  { number: '02', icon: BrainCircuit, accent: 'yellow', title: 'Intelligence augmentée', text: 'Nous transformons la donnée en décisions claires grâce à l’IA, l’automatisation et des usages qui restent humains.', tags: ['Data', 'IA générative', 'Automatisation'] },
  { number: '03', icon: Cloud, accent: 'red', title: 'Cloud & cybersécurité', text: 'Une infrastructure solide, souple et protégée pour faire grandir vos ambitions sans ralentir votre quotidien.', tags: ['Cloud', 'DevOps', 'Audit sécurité'] },
]

function Logo({ compact = false }) {
  return <a className={`brand ${compact ? 'brand-compact' : ''}`} href="#top" aria-label="J@mbAR_Xarala, accueil"><span className="brand-mark"><span>J</span><b>×</b></span><span className="brand-name">J@mbAR<span>_Xarala</span></span></a>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const closeMenu = () => setMenuOpen(false)
  return <div className="site-shell professional-site" id="top">
    <div className="utility-bar"><span>J@mbAR_Xarala · Bureau d’innovation numérique</span><span><Globe2 size={13} /> Dakar · Sénégal <b>FR</b> <span className="utility-muted">EN</span></span></div>
    <header className="site-header"><Logo compact /><nav className={menuOpen ? 'main-nav open' : 'main-nav'} aria-label="Navigation principale"><a href="#expertise" onClick={closeMenu}>Nos expertises</a><a href="#solutions" onClick={closeMenu}>Solutions</a><a href="#approche" onClick={closeMenu}>Notre approche</a><a href="#agence" onClick={closeMenu}>L’agence</a><a href="#contact" onClick={closeMenu}>Contact</a></nav><a className="header-cta" href="#contact">Démarrer un projet <ArrowUpRight size={16} /></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></header>
    <main>
      <section className="hero-section pro-hero"><div className="hero-content"><div className="eyebrow"><span className="pulse-dot" /> L’innovation numérique, notre ADN</div><h1>Le digital qui<br /><em>fait avancer.</em></h1><p className="hero-copy">Nous accompagnons les organisations africaines dans leur transformation avec des solutions numériques utiles, ambitieuses et conçues au Sénégal.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Parler de votre projet <ArrowRight size={18} /></a><a className="text-link" href="#expertise">Découvrir J@mbAR_Xarala <ChevronDown size={16} /></a></div><div className="hero-trust"><span>Ils nous font confiance pour</span><b>transformer leurs idées en impact</b></div></div><div className="hero-media"><div className="media-frame"><img src="/jambar-logo.jpeg" alt="Identité J@mbAR_Xarala" /><div className="media-overlay"><span>01</span><b>Innovation<br />made in Dakar</b></div></div><div className="media-note"><span className="flag-stripe" /> Une vision locale.<br /><strong>Une portée mondiale.</strong></div></div></section>
      <section className="proof-strip"><div><strong>01</strong><span>vision stratégique<br />et exécution</span></div><div><strong>04</strong><span>expertises réunies<br />en une équipe</span></div><div><strong>100%</strong><span>engagement pour<br />votre transformation</span></div><a href="#contact">Nous connaître <ArrowUpRight size={17} /></a></section>
      <section className="intro-section pro-intro" id="expertise"><div className="section-label">01 / Qui sommes-nous</div><div className="intro-layout"><div><h2>La technologie<br /><span>au service du réel.</span></h2><div className="accent-rule" /></div><div className="intro-body"><p className="lead">J@mbAR_Xarala est un bureau de solutions et d’innovation informatique basé à Dakar. Nous réunissons conseil, design et ingénierie pour créer des expériences digitales qui répondent à de vrais enjeux.</p><a className="arrow-link" href="#agence">Découvrir notre vision <span><ArrowUpRight size={16} /></span></a></div></div><div className="expertise-highlight"><div><span>01</span><h3>Comprendre<br /><em>avant de construire.</em></h3></div><p>Nous commençons par vos objectifs, vos équipes et vos utilisateurs. La bonne solution n’est pas la plus complexe : c’est celle qui produit des résultats.</p><a href="#contact"><ArrowUpRight size={20} /></a></div></section>
      <section className="solutions-section" id="solutions"><div className="section-heading"><div><div className="section-label">02 / Nos expertises</div><h2>Des compétences<br /><span>qui font la différence.</span></h2></div><p>De la stratégie au déploiement, nous construisons avec vous les fondations d’une croissance numérique durable.</p></div><div className="solution-grid">{solutions.map(({ number, icon: Icon, accent, title, text, tags }) => <article className="solution-card" key={number}><div className={`solution-top ${accent}`}><span>{number}</span><Icon size={25} strokeWidth={1.5} /></div><h3>{title}</h3><p>{text}</p><div className="tag-list">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div><a href="#contact" className="card-link" aria-label={`En savoir plus sur ${title}`}><ArrowUpRight size={20} /></a></article>)}</div></section>
      <section className="approach-section pro-approach" id="approche"><div className="approach-copy"><div className="section-label">03 / Notre méthode</div><h2>Un cadre clair.<br /><span>Des résultats concrets.</span></h2><p>Une transformation réussie avance par étapes. Nous faisons équipe avec vos collaborateurs à chaque moment important.</p><div className="method-list"><div><b>01</b><span><strong>Écouter</strong><small>Vos enjeux, vos utilisateurs, votre terrain.</small></span><CheckCircle2 size={19} /></div><div><b>02</b><span><strong>Concevoir</strong><small>Une expérience simple, désirable et viable.</small></span><CheckCircle2 size={19} /></div><div><b>03</b><span><strong>Développer</strong><small>Avec une technologie fiable et évolutive.</small></span><CheckCircle2 size={19} /></div><div><b>04</b><span><strong>Transmettre</strong><small>Pour que vos équipes restent autonomes.</small></span><CheckCircle2 size={19} /></div></div></div><div className="approach-visual pro-visual"><div className="visual-card"><span>JX</span><small>DESIGNING<br />AFRICAN<br />POSSIBILITIES</small><div className="visual-lines" /></div><div className="visual-corner">Dakar<br />14°43′N</div></div></section>
      <section className="sectors-section" id="agence"><div className="section-label">04 / Là où nous intervenons</div><div className="sectors-heading"><h2>Des solutions pour<br /><span>ceux qui construisent.</span></h2><p>Nous travaillons avec des entreprises, institutions et entrepreneurs qui veulent transformer leur façon de créer de la valeur.</p></div><div className="sector-grid"><div><Landmark size={22} /><span>Institutions<br /><b>& territoires</b></span></div><div><Users size={22} /><span>Entreprises<br /><b>en croissance</b></span></div><div><PanelsTopLeft size={22} /><span>Startups<br /><b>et projets innovants</b></span></div><div><Network size={22} /><span>Écosystèmes<br /><b>africains</b></span></div></div></section>
      <section className="impact-section pro-impact" id="impact"><div className="section-label">05 / Notre engagement</div><div className="impact-heading"><h2>Le futur africain<br /><span>se construit ici.</span></h2><p>La technologie n’est pas une destination. C’est un levier pour rendre les organisations plus fortes, plus agiles et plus proches de leurs communautés.</p></div><div className="metrics"><div><strong>01</strong><span>ancrage local<br />et regard global</span></div><div><strong>04</strong><span>métiers au service<br />d’une même vision</span></div><div><strong>∞</strong><span>possibilités<br />à inventer</span></div></div></section>
      <section className="contact-section pro-contact" id="contact"><div className="contact-intro"><div className="section-label">06 / Parlons-nous</div><h2>Un projet qui<br /><span>mérite d’avancer ?</span></h2><p>Présentez-nous votre idée. Nous vous répondrons avec une première piste de réflexion sous 48 heures.</p><div className="contact-detail"><span>hello@jambar-xarala.sn</span><span>+221 77 000 00 00</span></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}>{!submitted ? <><label>Votre nom <input required type="text" placeholder="Awa Diop" /></label><label>Votre adresse email <input required type="email" placeholder="awa@entreprise.sn" /></label><label>Votre besoin <textarea required rows="3" placeholder="Parlez-nous de votre projet..." /></label><button className="button button-primary" type="submit">Envoyer ma demande <ArrowUpRight size={18} /></button></> : <div className="success-state"><div><Check size={24} /></div><h3>Merci pour votre message.</h3><p>Notre équipe revient vers vous très vite.</p></div>}</form></section>
    </main>
    <footer className="site-footer"><Logo /><span>© 2026 J@mbAR_Xarala · Dakar, Sénégal</span><div><a href="#agence">L’agence</a><a href="#contact">Contact</a><a href="#top">Retour en haut ↑</a></div></footer>
  </div>
}

export default App

createRoot(document.getElementById('root')).render(<App />)
